# Generated by Django 4.1.7 on 2023-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group_name',
            field=models.TextField(default=None, null=True),
        ),
    ]
