# Generated by Django 4.1.7 on 2023-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_choice_question_alter_question_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='istext',
            field=models.BooleanField(default=False),
        ),
    ]
