# Generated by Django 4.1.7 on 2023-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_question_istext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="group_name",
            field=models.TextField(default="Not provided", null=True),
        ),
    ]
