# Generated by Django 4.1.7 on 2023-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_alter_customuser_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
