# Generated by Django 4.1.7 on 2023-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0007_surveyresponse_is_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="group",
            field=models.CharField(default="Notprovided", max_length=300),
        ),
    ]
