# Generated by Django 4.1.7 on 2023-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0008_surveyresponse_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyresponse",
            name="group",
        ),
    ]
