# Generated by Django 4.1.7 on 2023-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0009_remove_surveyresponse_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="group_name_required",
            field=models.BooleanField(default=False),
        ),
    ]
