# Generated by Django 4.1.7 on 2023-03-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_survey_group_name_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='group_name_required',
        ),
    ]
