# Generated by Django 4.1.7 on 2023-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_survey_group_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='responder_info_required',
            field=models.BooleanField(default=True),
        ),
    ]
